language: node_js
node_js:
  - "lts/dubnium"
  - "lts/erbium"
  - "node"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 'node'
services:
      - mongodb
script:
  - npm test
after_success:
  - npm run coverage
